SELECT COUNT(ID) AS COUNT FROM ECOLI_DATA
WHERE ID NOT IN (SELECT ID FROM ECOLI_DATA
    WHERE CONV(GENOTYPE, 10, 2) LIKE '%1_') 
AND (CONV(GENOTYPE, 10, 2) LIKE '%1__' OR CONV(GENOTYPE, 10, 2) LIKE '%1')
