# SELECT COUNT(ID) AS COUNT FROM ECOLI_DATA
# WHERE ID NOT IN (SELECT ID FROM ECOLI_DATA
#     WHERE CONV(GENOTYPE, 10, 2) LIKE '%1_') 
# AND (CONV(GENOTYPE, 10, 2) LIKE '%1__' OR CONV(GENOTYPE, 10, 2) LIKE '%1')

WITH BIN AS (
  SELECT ID, CONV(GENOTYPE, 10, 2) AS GENO
  FROM ECOLI_DATA
)

SELECT COUNT(ID) AS COUNT 
FROM BIN
WHERE GENO NOT LIKE '%1_' AND (GENO LIKE '%1__' OR GENO LIKE '%1')