# 수원지역, 연도별, 평균 미세먼지 오염도(PM10), 평균 초미세먼지 오염도(PM2.5)
# ROUND(#, 3)
# ORDER BY 연도

SELECT YEAR(YM) AS YEAR, ROUND(AVG(PM_VAL1), 2) AS "PM10", ROUND(AVG(PM_VAL2), 2) AS "PM2.5" 
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원'
GROUP BY YEAR
ORDER BY YEAR