# WITH SALES_COUNT AS (
#     SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
#     FROM OFFLINE_SALE
#     GROUP BY PRODUCT_ID
# )

# SELECT P.PRODUCT_CODE, (P.PRICE * C.SALES_AMOUNT) AS SALES
# FROM PRODUCT AS P
# JOIN SALES_COUNT AS C ON P.PRODUCT_ID = C.PRODUCT_ID
# ORDER BY SALES DESC, P.PRODUCT_CODE

SELECT product_code, SUM(price * sales_amount) AS sales 
FROM product P JOIN offline_sale O ON P.product_id = O.product_id
GROUP BY product_code
ORDER BY sales DESC, product_code;