WITH RENTAL_UNABLE_CARS AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
      AND END_DATE >= '2022-11-01'
),  
DISCOUNT_DAILY_FEE AS (
    SELECT CAR_TYPE, 1 - (CAST(REPLACE(DISCOUNT_RATE, '%', '') AS UNSIGNED) / 100) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
      AND CAR_TYPE IN ('세단', 'SUV')
)

SELECT 
    A.CAR_ID, 
    A.CAR_TYPE, 
    FLOOR(A.DAILY_FEE * 30 * C.DISCOUNT_RATE) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
LEFT JOIN RENTAL_UNABLE_CARS AS B ON A.CAR_ID = B.CAR_ID
JOIN DISCOUNT_DAILY_FEE AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE B.CAR_ID IS NULL
  AND FLOOR(A.DAILY_FEE * 30 * C.DISCOUNT_RATE) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;
