WITH SIZE_RANK AS (
    SELECT ID, SIZE_OF_COLONY 
    FROM ECOLI_DATA
    ORDER BY SIZE_OF_COLONY DESC
)

SELECT
    ID,
    CASE 
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) 
        WHEN 1 THEN 'LOW'
        WHEN 2 THEN 'MEDIUM'
        WHEN 3 THEN 'HIGH'
        WHEN 4 THEN 'CRITICAL'
    END AS COLONY_NAME
FROM SIZE_RANK
ORDER BY ID