WITH MAX_SIZE_PER_YEAR AS (SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    MAX(SIZE_OF_COLONY) AS MAX
FROM 
    ECOLI_DATA
GROUP BY 
    YEAR(DIFFERENTIATION_DATE))
    
SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (B.MAX - A.SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM ECOLI_DATA A
JOIN MAX_SIZE_PER_YEAR B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV
