# WITH MAX_SIZE_PER_YEAR AS (SELECT 
#     YEAR(DIFFERENTIATION_DATE) AS YEAR, 
#     MAX(SIZE_OF_COLONY) AS MAX
# FROM 
#     ECOLI_DATA
# GROUP BY 
#     YEAR(DIFFERENTIATION_DATE))
    
# SELECT
#     YEAR(DIFFERENTIATION_DATE) AS YEAR,
#     (B.MAX - A.SIZE_OF_COLONY) AS YEAR_DEV,
#     ID
# FROM ECOLI_DATA A
# JOIN MAX_SIZE_PER_YEAR B
# ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
# ORDER BY YEAR, YEAR_DEV



SELECT YEAR(A.DIFFERENTIATION_DATE) AS year, (max - size_of_colony) AS year_dev, id 
FROM ecoli_data A
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS year, MAX(size_of_colony) as max 
    FROM ecoli_data
    GROUP BY YEAR(DIFFERENTIATION_DATE)) B
ON YEAR(A.DIFFERENTIATION_DATE) = B.year
ORDER BY year, year_dev